CREATE TABLE public.math_problem
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    department character varying(255) NOT NULL,
    points integer NOT NULL,
    level character varying(255) NOT NULL,
    image_data oid NOT NULL,
    CONSTRAINT math_problem_pkey PRIMARY KEY (id)
)